# Generated by Django 5.2.2 on 2025-06-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='name',
            new_name='instructor_id',
        ),
    ]
