# Generated by Django 5.2.2 on 2025-06-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_name_instructor_instructor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0, help_text='month of experience.'),
        ),
    ]
