# Generated by Django 5.2.2 on 2025-06-08 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_instructor_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor_id',
        ),
        migrations.AddField(
            model_name='instructor',
            name='user_instructor',
            field=models.OneToOneField(help_text='Instructor', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
