# Generated by Django 5.2.2 on 2025-06-08 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_instructor_instructor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessclass',
            options={'verbose_name': 'Fitness Class', 'verbose_name_plural': 'Fitness Classes'},
        ),
        migrations.CreateModel(
            name='BookSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='automaticaly set when model created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='automaticaly updated when model saved')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.OneToOneField(help_text='Client for fitness slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fitness', models.ManyToManyField(help_text='fitness class for client.', to='book.instructor')),
            ],
            options={
                'verbose_name': 'Book Slot',
                'verbose_name_plural': 'Book Slots',
            },
        ),
    ]
