# Generated by Django 5.2.2 on 2025-06-08 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_fitnessclass_options_bookslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookSlot',
            new_name='BookingSlot',
        ),
        migrations.AlterModelOptions(
            name='bookingslot',
            options={'verbose_name': 'Booking Slot', 'verbose_name_plural': 'Booking Slots'},
        ),
    ]
