# Generated by Django 5.2.2 on 2025-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_bookslot_bookingslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='fitness',
            field=models.ManyToManyField(help_text='fitness class for client.', to='book.fitnessclass'),
        ),
    ]
