# Generated by Django 5.2.2 on 2025-06-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_bookingslot_fitness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingslot',
            old_name='fitness',
            new_name='fitness_class',
        ),
    ]
