# Generated by Django 5.2.2 on 2025-06-08 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_fitness_bookingslot_fitness_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='client',
            field=models.ForeignKey(help_text='Client for fitness slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bookingslot',
            name='fitness_class',
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='fitness_class',
            field=models.ForeignKey(help_text='fitness class for client.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.fitnessclass'),
        ),
    ]
