# Generated by Django 5.2.2 on 2025-06-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookingslot_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingslot',
            name='fitness_class',
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='fitness_class',
            field=models.ManyToManyField(help_text='fitness class for client.', to='book.fitnessclass'),
        ),
    ]
